# fly.toml app configuration file generated for nodejs-download-stats on 2024-07-19T17:08:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nodejs-download-stats'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3042
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
